### ISSUE TITLE
Nonfunctional Bedrock Support & Container Root

### ISSUE THREAD

**Issue by xithical** [binhex/arch-crafty-4#1] opened 2022-06-17 15:04 UTC
Hi! Leadership member of the Crafty team here.

We added Bedrock support in v4, which your image will not work with as it does not have the required dependencies since they are not packaged with Arch and need installed separately. Further, we actually have an official image (see [our GitLab registry](https://gitlab.com/crafty-controller/crafty-4/container_registry/)).

We also have received some reports about people running into our root check that are possibly using your image - from what I can tell, it looks like their containers are running as UID 0, so our root check is preventing it from running as a deliberate security feature we built in; this may just be a red herring, though.

**Comment by xithical** [comment] 2022-06-17 15:05
As an addendum, Freddy0, our resident unRAID staff, actually published our official v4 build as an unRAID app a few days ago.

**Comment by binhex** [comment] 2022-06-17 20:23
Hi @xithical firstly let me say i don't want to cause you or the Crafty dev's any additional support headaches, if my image is causing you or the team problems then i will remove it from unRAID CA.

So i wasn't aware that Craft v4 supports Bedrock, so that is cool, but as you stated it looks to be Ubuntu only which is a problem for me (Arch Linux base os). 

The problem about running as root is a user configuration issue, my images can run as any user (including root), for unRAID they are set by default to run as user 'nobody' group' users', the defined user and group is controlled via PUID and PGID.

Finally i want to say i am impressed with Crafty v4, even as a beta release it seems very stable, so congrats on the work done.

**Comment by xithical** [comment] 2022-06-18 19:45
@binhex Thanks for getting back with me and thank you for the congrats - our dev team is truly fantastic!

I think for simplicity's sake it would be better to just have our official image published. We'd love to have you work with Freddy on keeping our own image maintained for unRAID, though; if you're open to that idea, feel free to pop into [our Discord](https://discord.gg/9VJPhCE) and say hello!

**Comment by binhex** [comment] 2022-06-20 18:37
Hi @xithical i took a quick poke around to see what the issue is with Bedrock on my image and couldnt really find much wrong other than the missing ports (corrected), once i had done this then i could successfully import a Bedrock server, see it was running and connect to it using Minecraft PE running on Android, so unless im missing something i dont think there are any issues with Arch Linux and the Bedrock support for Crafty 4, please correct me if im wrong.

**Comment by binhex** [comment] 2022-07-06 09:20
im going to close this issue, the running as root issue was purely a configuration issue for users where they were using the example PUID and PGID values which were both 0 (root), i have amended the examples to be 99 and 100 respectively and put a note in recommending NOT to run as root.

as for the issue with running bedrock servers, i currently see no problems with this and am currently running a bedrock server using crafty-4 with no obvious issues, please create a new issue if this is still causing problems for end users.

**Closed as completed by binhex** 2022-07-06 09:20 UTC
